name: fyp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  #  REQUIRED for i18n (EN/NE) support
  flutter_localizations:
    sdk: flutter

  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^18.0.1
  google_sign_in: ^6.2.1

  intl: ^0.20.2

  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dotted_border: ^2.1.0
  file_picker: ^8.0.0
  flutter_riverpod: ^2.5.1
  provider: ^6.1.2
  image_picker: ^1.0.7
  esewa_flutter_sdk: ^2.0.1
  pdf: ^3.10.8
  printing: ^5.13.4
  path_provider: ^2.1.4
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  file_saver: ^0.2.14
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^33.1.44
  url_launcher: ^6.3.0

  # Maps + tracking
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  socket_io_client: ^2.0.3+1
  http: ^1.2.2

  # Firebase Storage for profile images
  firebase_storage: ^12.4.6

  # Image caching with error handling
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  esewa_flutter_sdk:
    path: third_party/esewa_flutter_sdk

flutter:
  uses-material-design: true


  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf