import 'dart:typed_data';
import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'payment_receipt_service.dart';

class PaymentReceiptPdfService {
  static pw.Font? _regular;
  static pw.Font? _bold;

  static Future<void> _loadFonts() async {
    if (_regular != null && _bold != null) return;

    final regData = await rootBundle.load('assets/fonts/Roboto-Regular.ttf');
    final boldData = await rootBundle.load('assets/fonts/Roboto-Bold.ttf');

    _regular = pw.Font.ttf(regData);
    _bold = pw.Font.ttf(boldData);
  }

  static Future<Uint8List> buildPdf(PaymentReceipt r) async {
    await _loadFonts();

    final doc = pw.Document();

    final fmt = DateFormat('MMM dd, yyyy • h:mm a');
    final dateLabel = fmt.format(r.dateTime.toLocal());

    final theme = pw.ThemeData.withFont(
      base: _regular!,
      bold: _bold!,
    );

    doc.addPage(
      pw.Page(
        theme: theme,
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (_) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                "Payment Receipt",
                style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 6),
              pw.Text(
                "Payment Successful",
                style: pw.TextStyle(fontSize: 13, color: PdfColors.green800),
              ),
              pw.SizedBox(height: 12),
              pw.Divider(),

              _row("Transaction ID", r.transactionId),
              _row("Date & Time", dateLabel),
              _row("Payment Method", r.paymentMethod),
              _row("Recipient", r.recipient),
              _row("Service", r.service),
              _row("Quantity", "${r.quantityLiters} L"),
              _row("Amount", "NPR ${r.amount.toStringAsFixed(2)}"),

              pw.Spacer(),
              pw.Divider(),
              pw.Text(
                "Generated by Hamro Pani",
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
              ),
            ],
          );
        },
      ),
    );

    return doc.save();
  }

  static pw.Widget _row(String k, String v) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            flex: 4,
            child: pw.Text(
              k,
              style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
            ),
          ),
          pw.SizedBox(width: 12),
          pw.Expanded(
            flex: 6,
            child: pw.Text(
              v,
              textAlign: pw.TextAlign.right,
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }
}